package ClientUI;

import com.sun.org.apache.xpath.internal.operations.String;

import javax.swing.*;

/**
 *
 * @author iljab
 */
public class PortUI extends javax.swing.JFrame {

    /**
     * Creates new form PortUI
     */
    private ClientWorker worker;
    public PortUI(ClientWorker s) {
        this.worker = s;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Установка порта");
    }

    public PortUI(ClientWorker s, java.lang.String data){
        this.worker = s;
        JOptionPane.showMessageDialog(this,
                new java.lang.String[] {worker.getResource().getString(data)},
                worker.getResource().getString("ErrorTitle"),
                JOptionPane.ERROR_MESSAGE);
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Установка порта");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Хост");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Порт");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new java.lang.String[] { "Русский", "suomalainen", "Shqiptar", "Español(Ec)" }));
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox1ActionPerformed(evt);
                }
            });

            jButton1.setText("Запуск");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(13, 13, 13)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel1))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(36, 36, 36)
                                                    .addComponent(jButton1)))
                                    .addContainerGap(21, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        boolean catched = false;
        System.out.println("Port: "+jTextField1.getText());
        System.out.println("Host: "+jTextField2.getText());
            java.lang.String host =jTextField1.getText();
        int port = 0;
        try {
            port = Integer.valueOf(jTextField2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    new java.lang.String[] {worker.getResource().getString("WrongPortError")},
                    worker.getResource().getString("ErrorTitle"),
                    JOptionPane.ERROR_MESSAGE);
            catched=true;

        }
        if (port>0 &&port<65535){
            setVisible(false);
            worker.endPortWork(host,port);

        }else if (!catched){
            JOptionPane.showMessageDialog(this,
                    new java.lang.String[] {worker.getResource().getString("WrongPortNumberError")},
                    worker.getResource().getString("ErrorTitle"),
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        int index =jComboBox1.getSelectedIndex();
        switch (index) {
            case 0:
                System.out.println("Выбран русский язык");
                worker.setLocale("ru");
                break;
            case 1:
                System.out.println("Выбран Финский язык");
                worker.setLocale("fi");
                break;
            case 2:
                System.out.println("Выбран лбанский язык");
                worker.setLocale("sq");
                break;
            case 3:
                System.out.println("Выбран испанский(Эквадор) язык");
                worker.setLocaleAnd("es","EC");
                break;
        }
        jComboBox1.setSelectedIndex(index);
        setText();

    }

    private void setText(){
        jComboBox1.setModel(new DefaultComboBoxModel(new java.lang.String[] {
            worker.getResource().getString("Russian"),
            worker.getResource().getString("Finnish"),
            worker.getResource().getString("Shqiptar"),
            worker.getResource().getString("Español(Ec)")
        }));
        jComboBox1.setSelectedIndex(worker.getLocale());
        jLabel1.setText(worker.getResource().getString("Host"));
        jLabel2.setText(worker.getResource().getString("Port"));
        jButton1.setText(worker.getResource().getString("Launch"));
        this.setTitle(worker.getResource().getString("PortSet"));


    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration
}
